#!/usr/bin/env bash
# run-limine.sh — launch Lythos under QEMU + OVMF (Limine UEFI boot).
#
# Usage:  ./run-limine.sh [OVMF_CODE.fd [OVMF_VARS.fd]]
#         KERNEL=<path>          override kernel (default: debug build)
#         EXTRA_QEMU_FLAGS=...   append extra flags (e.g. "-d int,cpu_reset")
#
# OVMF firmware:
#   QEMU 5.2+ (nix, brew): ships edk2-x86_64-code.fd in its share/qemu dir.
#   If OVMF_CODE is provided, explicit pflash drives are used.
#   If OVMF_CODE is empty (default), QEMU auto-loads firmware from its share dir
#   (QEMU 6+ Q35 machine detects edk2-x86_64-code.fd automatically).
#
# Prerequisites:
#   limine.img  — created by `make limine.img` (requires mtools + Limine EFI)
#     nix:       NIXPKGS_ALLOW_UNSUPPORTED_SYSTEM=1 nix-shell -p mtools
#     Linux:     nix-shell -p limine ovmf mtools  (or apt/pacman equivalents)
set -e

LYTHOS="$(cd "$(dirname "$0")" && pwd)"
KERNEL="${KERNEL:-$LYTHOS/target/x86_64-lythos/debug/lythos}"
DISK_IMG="$LYTHOS/disk.img"
# Persistent /shade/store backing. Fixed image, NO -snapshot: content must
# survive a full power cycle (QEMU restart against the SAME store.img) so a
# cold boot brings up a generation whose closure still exists. Created blank
# once if absent (the kernel formats it lazily at the first store mount) and
# NEVER regenerated by the build — that would silently erase persistence.
STORE_IMG="${STORE_IMG:-$LYTHOS/store.img}"
STORE_IMG_SIZE="${STORE_IMG_SIZE:-64M}"
BOOT_IMG="$LYTHOS/limine.img"
SOCK="/tmp/lythos-serial-$$.sock"

# OVMF_CODE / OVMF_VARS: explicit paths override auto-detection.
# Leave empty to let QEMU's Q35 machine auto-load firmware from its share dir.
# The two positional args are consumed here and MUST be shifted away —
# anything left in "$@" is appended verbatim to the qemu command line, and a
# bare firmware path there becomes a phantom IDE disk (index collision,
# "drive with bus=0, unit=0 (index=0) exists").
OVMF_CODE="${1:-${OVMF_CODE:-}}"
OVMF_VARS="${2:-${OVMF_VARS:-}}"
if [ $# -ge 1 ]; then shift; fi
if [ $# -ge 1 ]; then shift; fi

# ── Pre-flight checks ──────────────────────────────────────────────────────────
if [ ! -f "$BOOT_IMG" ]; then
    echo "error: $BOOT_IMG not found — run \`make limine.img\` first"
    exit 1
fi
if [ ! -f "$DISK_IMG" ]; then
    echo "warning: $DISK_IMG not found — virtio-blk and RFS will be absent"
    DISK_FLAGS=""
else
    DISK_FLAGS="-drive file=$DISK_IMG,format=raw,if=none,id=hd0 -device virtio-blk-pci,drive=hd0"
fi

# Persistent store device (instance 1). Create a blank raw image once; the
# kernel formats RFS2 onto it at the first /shade/store mount, and every
# subsequent boot mounts the existing volume. Attached AFTER the root disk so
# it enumerates as the second virtio-blk device (DEV_STORE).
if [ ! -f "$STORE_IMG" ]; then
    echo "[run-limine.sh] creating blank persistent store image $STORE_IMG ($STORE_IMG_SIZE)"
    if command -v qemu-img >/dev/null 2>&1; then
        qemu-img create -f raw "$STORE_IMG" "$STORE_IMG_SIZE" >/dev/null
    else
        # Fallback: sparse file via truncate (64M default).
        truncate -s "$STORE_IMG_SIZE" "$STORE_IMG"
    fi
fi
STORE_FLAGS="-drive file=$STORE_IMG,format=raw,if=none,id=hd1 -device virtio-blk-pci,drive=hd1"

cleanup() {
    kill "$QPID" 2>/dev/null || true
    rm -f "$SOCK" "$BRIDGE" /tmp/lythos-ovmf-vars.fd
}
trap cleanup EXIT

# ── OVMF pflash configuration ──────────────────────────────────────────────────
# QEMU 6+ Q35 auto-loads edk2-x86_64-code.fd from its share dir; explicit
# pflash drives conflict with that auto-config.  Only add -drive if=pflash
# when the user explicitly provides OVMF_CODE (non-default installs).
if [ -n "$OVMF_CODE" ] && [ -f "$OVMF_CODE" ]; then
    cp "${OVMF_VARS:-$OVMF_CODE}" /tmp/lythos-ovmf-vars.fd
    chmod 644 /tmp/lythos-ovmf-vars.fd
    OVMF_FLAGS="-drive if=pflash,format=raw,unit=0,file=${OVMF_CODE},readonly=on \
                -drive if=pflash,format=raw,unit=1,file=/tmp/lythos-ovmf-vars.fd"
else
    OVMF_FLAGS=""
fi

# ── Launch QEMU ────────────────────────────────────────────────────────────────
# -m: QEMU's default 128 MiB is too small for Limine 11's high-memory
# allocator to load the ~8 MB debug kernel ("PANIC: High memory allocator:
# Out of memory"). Override with QEMU_MEM=...
qemu-system-x86_64 \
    -machine q35,usb=on \
    -m "${QEMU_MEM:-512M}" \
    $OVMF_FLAGS \
    -drive  file="$BOOT_IMG",format=raw,if=none,id=esp \
    -device usb-storage,drive=esp \
    $DISK_FLAGS \
    $STORE_FLAGS \
    -netdev user,id=net0 \
    -device virtio-net-pci,netdev=net0 \
    -chardev socket,id=s0,path="$SOCK",server=on,wait=on \
    -serial  chardev:s0 \
    -display none \
    ${EXTRA_QEMU_FLAGS:-} \
    "$@" &
QPID=$!

for i in $(seq 1 50); do
    [ -S "$SOCK" ] && break
    sleep 0.1
done

if [ ! -S "$SOCK" ]; then
    echo "[run-limine.sh] error: QEMU socket not created" >&2
    exit 1
fi

# Serial console bridge: connect the terminal to QEMU's unix serial socket in
# raw-ish mode (no echo, char-at-a-time, signals still delivered to this bridge
# so Ctrl-C detaches rather than reaching the guest). Prefer python3; fall back
# to socat, then nc, so hosts without python (e.g. the nix devShell) still work.
if command -v python3 >/dev/null 2>&1; then
BRIDGE="$(mktemp)"
cat > "$BRIDGE" <<'PYEOF'
import socket, sys, os, select, termios

path = sys.argv[1]
sock = socket.socket(socket.AF_UNIX, socket.SOCK_STREAM)
sock.connect(path)

old_attrs = termios.tcgetattr(0)
new_attrs = termios.tcgetattr(0)
new_attrs[0] &= ~(termios.IGNBRK | termios.BRKINT | termios.PARMRK |
                  termios.ISTRIP | termios.INLCR | termios.IGNCR |
                  termios.ICRNL | termios.IXON)
new_attrs[1] |=  termios.OPOST | termios.ONLCR
new_attrs[2] &= ~termios.CSIZE
new_attrs[2] |=  termios.CS8
new_attrs[3] &= ~(termios.ECHO | termios.ECHONL | termios.ICANON | termios.IEXTEN)
new_attrs[3] |=  termios.ISIG
new_attrs[6][termios.VMIN]  = 1
new_attrs[6][termios.VTIME] = 0
termios.tcsetattr(0, termios.TCSADRAIN, new_attrs)

try:
    while True:
        r, _, _ = select.select([0, sock], [], [])
        if 0 in r:
            data = os.read(0, 256)
            if not data:
                break
            sock.sendall(data)
        if sock in r:
            data = sock.recv(4096)
            if not data:
                break
            os.write(1, data)
except (KeyboardInterrupt, BrokenPipeError, OSError):
    pass
finally:
    termios.tcsetattr(0, termios.TCSADRAIN, old_attrs)
PYEOF
    python3 "$BRIDGE" "$SOCK"
elif command -v socat >/dev/null 2>&1; then
    # -,echo=0,icanon=0: no local echo, char-at-a-time; isig stays on so host
    # Ctrl-C interrupts socat instead of being forwarded to the guest.
    socat -,echo=0,icanon=0 UNIX-CONNECT:"$SOCK"
elif command -v nc >/dev/null 2>&1; then
    nc -U "$SOCK"
else
    echo "[run-limine.sh] error: no serial bridge available (need python3, socat, or nc)" >&2
    exit 1
fi
